name: 🐛 Bug Report
description: 동작 이상을 신고합니다
labels: ["bug"]
body:
  - type: input
    attributes:
      label: 패키지 버전
      placeholder: "0.2.1"
    validations:
      required: true
  - type: input
    attributes:
      label: Node 버전
      placeholder: "v20.10.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 재현 절차
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 기대 동작 vs 실제 동작
    validations:
      required: true
